### ISSUE TITLE
Lenses should include a human-readable name

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/lens-selector-mvp2#5]
Maybe in the getSpecification() function, instead of returning a string version, return a full object with the speciffication.
This is my proposal (using diabetes lens as example):
```js
let getSpecification = () => {
    return {
      id: "lens-selector-mvp2_diabetes",
      name: "Diabetes",
      version: "1.0.0"
    }
}

This way, clients can present a human-readable name for the lenses. We can expand this specifications in the future or for MVP3.
```

**Comment by amedranogil** [comment]
lenses should be languaje agnostic, because they should only look into annotations (which are languaje agnostic). But I do agree that human-readable label, description, and version of the lens it self.
The important aspect is that this function was meant for the LEE to know which specification is the lens compatible with, I.E which version of the LEE should the lens operate with; not so much as to know different aspects of the lens it self, for that we could add new functions in next version (specification) which covers what you propose; that way getSpecification is allways the same, but if lens is compatible with latest specification, then it can also provide extra information.

**Comment by gmej** [comment]
Will be solved in [gravitate-health/29](https://github.com/hl7-eu/gravitate-health/issues/29)
